import { setBackend } from 'o1js';
setBackend('native');

import { Edwards25519, Eddsa, eddsa, Bytes32 } from './eddsa.js';
import { initializeBindings, Cache } from 'o1js';
import { derivePublicKey } from '../src/index.js';
import assert from 'assert';

await initializeBindings();

// create an example EdDSA keypair (RFC 8032: seed -> SHA-512 -> scalar -> public key)
let seed = Edwards25519.Scalar.random();
let publicKey = new Edwards25519(derivePublicKey(seed.toBigInt()));

let message = Bytes32.fromString("what's up");
let signature = Eddsa.sign(message.toBytes(), seed.toBigInt());

// investigate the constraint system generated by EdDSA verify
console.time('eddsa verify only (build constraint system)');
let csEddsa = await eddsa.analyzeMethods();
console.timeEnd('eddsa verify only (build constraint system)');
console.log(csEddsa.verifyEddsa.summary());
console.log('Total rows:', csEddsa.verifyEddsa.rows);

// compile and prove with native prover
await eddsa.compile({ cache: Cache.None });

console.time('eddsa verify (prove)');
let { proof } = await eddsa.verifyEddsa(message, signature, publicKey);
console.timeEnd('eddsa verify (prove)');

proof.publicOutput.assertTrue('signature verifies');
assert(await eddsa.verify(proof), 'proof verifies');
